name: paintroid
description: The standard image manipulation app for Catroid.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  equatable: ^2.0.3
  flutter_svg: ^1.1.0
  image: ^3.2.0
  protobuf: ^2.1.0
  path: ^1.8.1
  path_provider: ^2.0.11
  flutter_riverpod: ^1.0.4
  image_picker: ^0.8.5+3
  oxidized: ^5.2.0
  logging: ^1.0.2
  file_picker: ^4.6.1
  flutter_styled_toast: ^2.1.3
  floor: ^1.2.0
  filesize: ^2.0.1
  sqflite:
  permission_handler: ^10.0.0
  url_launcher: ^6.1.5
  package_info_plus: ^1.4.0
  launch_review: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.2.0
  build_runner: ^2.2.0
  flutter_launcher_icons: ^0.9.3
  flutter_lints: ^2.0.1
  floor_generator: ^1.2.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/svg/
    - test/fixture/image/